"""Q18 subjects: the cached LLM-derived visual subject per gap product.

`app.services.icon_subjects` reads `app/resources/icon_subjects.json`, generated by
`scripts/propose_icon_subjects.py` (the LLM gateway, run once and reviewed by the operator),
and normalizes lookups the same way `icon_briefs.py` does. Nothing here ever calls the
gateway - that is the script's job, not this module's.
"""

from __future__ import annotations

import json

import app.services.icon_subjects as icon_subjects
from app.services.icon_subjects import subject_for


def _write_cache(tmp_path, monkeypatch, data: dict) -> None:
    path = tmp_path / "icon_subjects.json"
    path.write_text(json.dumps(data), encoding="utf-8")
    monkeypatch.setattr(icon_subjects, "_PATH", path)
    icon_subjects._cache.cache_clear()


class TestSubjectFor:
    def test_an_unknown_product_has_no_cached_subject(
        self, tmp_path, monkeypatch
    ) -> None:
        _write_cache(tmp_path, monkeypatch, {})

        assert subject_for("Quark") is None

    def test_a_cached_product_is_found(self, tmp_path, monkeypatch) -> None:
        _write_cache(
            tmp_path, monkeypatch, {"Quark": "a tub of smooth white soft cheese"}
        )

        assert subject_for("Quark") == "a tub of smooth white soft cheese"

    def test_the_lookup_is_case_and_space_insensitive(
        self, tmp_path, monkeypatch
    ) -> None:
        _write_cache(
            tmp_path, monkeypatch, {"Quark": "a tub of smooth white soft cheese"}
        )

        assert subject_for("  QUARK  ") == "a tub of smooth white soft cheese"

    def test_a_missing_cache_file_is_treated_as_empty(
        self, tmp_path, monkeypatch
    ) -> None:
        monkeypatch.setattr(icon_subjects, "_PATH", tmp_path / "does_not_exist.json")
        icon_subjects._cache.cache_clear()

        assert subject_for("Quark") is None

    def test_blank_or_non_string_entries_are_ignored(
        self, tmp_path, monkeypatch
    ) -> None:
        _write_cache(tmp_path, monkeypatch, {"Quark": "   ", "Leek": 5})

        assert subject_for("Quark") is None
        assert subject_for("Leek") is None

    def test_a_malformed_cache_file_is_treated_as_empty(
        self, tmp_path, monkeypatch
    ) -> None:
        path = tmp_path / "icon_subjects.json"
        path.write_text("not json at all", encoding="utf-8")
        monkeypatch.setattr(icon_subjects, "_PATH", path)
        icon_subjects._cache.cache_clear()

        assert subject_for("Quark") is None

    def test_a_json_list_instead_of_an_object_is_treated_as_empty(
        self, tmp_path, monkeypatch
    ) -> None:
        path = tmp_path / "icon_subjects.json"
        path.write_text("[1, 2, 3]", encoding="utf-8")
        monkeypatch.setattr(icon_subjects, "_PATH", path)
        icon_subjects._cache.cache_clear()

        assert subject_for("Quark") is None
