"""Initial database schema with timezone-aware datetimes

Revision ID: c943e915cf61
Revises: 
Create Date: 2026-01-05 20:44:16.596363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c943e915cf61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('default_shelf_life_days', sa.Integer(), nullable=False),
    sa.Column('meal_contexts', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_table('receipt',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_chain', sa.String(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('ocr_raw_text', sa.Text(), nullable=True),
    sa.Column('ocr_structured', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('items_extracted', sa.Integer(), nullable=False),
    sa.Column('items_matched', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_batch_id'), 'receipt', ['batch_id'], unique=False)
    op.create_index(op.f('ix_receipt_id'), 'receipt', ['id'], unique=False)
    op.create_index(op.f('ix_receipt_processing_status'), 'receipt', ['processing_status'], unique=False)
    op.create_index(op.f('ix_receipt_store_chain'), 'receipt', ['store_chain'], unique=False)
    op.create_table('product_master',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('storage_type', sa.String(), nullable=False),
    sa.Column('default_shelf_life_days', sa.Integer(), nullable=False),
    sa.Column('opened_shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('unit_type', sa.String(), nullable=False),
    sa.Column('default_unit', sa.String(), nullable=False),
    sa.Column('default_quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('min_stock_quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reorder_quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('off_product_id', sa.String(), nullable=True),
    sa.Column('off_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_master_canonical_name'), 'product_master', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_product_master_category'), 'product_master', ['category'], unique=False)
    op.create_index(op.f('ix_product_master_id'), 'product_master', ['id'], unique=False)
    op.create_index(op.f('ix_product_master_off_product_id'), 'product_master', ['off_product_id'], unique=False)
    op.create_table('inventory_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_master_id', sa.UUID(), nullable=False),
    sa.Column('receipt_id', sa.UUID(), nullable=True),
    sa.Column('initial_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('expiry_source', sa.String(), nullable=False),
    sa.Column('opened_date', sa.Date(), nullable=True),
    sa.Column('batch_number', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_master_id'], ['product_master.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_item_expiry_date'), 'inventory_item', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_inventory_item_id'), 'inventory_item', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_item_product_master_id'), 'inventory_item', ['product_master_id'], unique=False)
    op.create_index(op.f('ix_inventory_item_receipt_id'), 'inventory_item', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_inventory_item_status'), 'inventory_item', ['status'], unique=False)
    op.create_table('shopping_list_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_master_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('is_purchased', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_master_id'], ['product_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_list_item_id'), 'shopping_list_item', ['id'], unique=False)
    op.create_index(op.f('ix_shopping_list_item_is_purchased'), 'shopping_list_item', ['is_purchased'], unique=False)
    op.create_index(op.f('ix_shopping_list_item_priority'), 'shopping_list_item', ['priority'], unique=False)
    op.create_index(op.f('ix_shopping_list_item_product_master_id'), 'shopping_list_item', ['product_master_id'], unique=False)
    op.create_index(op.f('ix_shopping_list_item_source'), 'shopping_list_item', ['source'], unique=False)
    op.create_table('store_product_alias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_master_id', sa.UUID(), nullable=False),
    sa.Column('store_chain', sa.String(), nullable=False),
    sa.Column('receipt_name', sa.String(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('manually_verified', sa.Boolean(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_master_id'], ['product_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_product_alias_barcode'), 'store_product_alias', ['barcode'], unique=False)
    op.create_index(op.f('ix_store_product_alias_id'), 'store_product_alias', ['id'], unique=False)
    op.create_index(op.f('ix_store_product_alias_product_master_id'), 'store_product_alias', ['product_master_id'], unique=False)
    op.create_index(op.f('ix_store_product_alias_receipt_name'), 'store_product_alias', ['receipt_name'], unique=False)
    op.create_index(op.f('ix_store_product_alias_store_chain'), 'store_product_alias', ['store_chain'], unique=False)
    op.create_table('consumption_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('product_master_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('quantity_consumed', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('consumption_context', sa.String(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_item.id'], ),
    sa.ForeignKeyConstraint(['product_master_id'], ['product_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumption_log_action'), 'consumption_log', ['action'], unique=False)
    op.create_index(op.f('ix_consumption_log_consumption_context'), 'consumption_log', ['consumption_context'], unique=False)
    op.create_index(op.f('ix_consumption_log_id'), 'consumption_log', ['id'], unique=False)
    op.create_index(op.f('ix_consumption_log_inventory_item_id'), 'consumption_log', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_consumption_log_logged_at'), 'consumption_log', ['logged_at'], unique=False)
    op.create_index(op.f('ix_consumption_log_product_master_id'), 'consumption_log', ['product_master_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consumption_log_product_master_id'), table_name='consumption_log')
    op.drop_index(op.f('ix_consumption_log_logged_at'), table_name='consumption_log')
    op.drop_index(op.f('ix_consumption_log_inventory_item_id'), table_name='consumption_log')
    op.drop_index(op.f('ix_consumption_log_id'), table_name='consumption_log')
    op.drop_index(op.f('ix_consumption_log_consumption_context'), table_name='consumption_log')
    op.drop_index(op.f('ix_consumption_log_action'), table_name='consumption_log')
    op.drop_table('consumption_log')
    op.drop_index(op.f('ix_store_product_alias_store_chain'), table_name='store_product_alias')
    op.drop_index(op.f('ix_store_product_alias_receipt_name'), table_name='store_product_alias')
    op.drop_index(op.f('ix_store_product_alias_product_master_id'), table_name='store_product_alias')
    op.drop_index(op.f('ix_store_product_alias_id'), table_name='store_product_alias')
    op.drop_index(op.f('ix_store_product_alias_barcode'), table_name='store_product_alias')
    op.drop_table('store_product_alias')
    op.drop_index(op.f('ix_shopping_list_item_source'), table_name='shopping_list_item')
    op.drop_index(op.f('ix_shopping_list_item_product_master_id'), table_name='shopping_list_item')
    op.drop_index(op.f('ix_shopping_list_item_priority'), table_name='shopping_list_item')
    op.drop_index(op.f('ix_shopping_list_item_is_purchased'), table_name='shopping_list_item')
    op.drop_index(op.f('ix_shopping_list_item_id'), table_name='shopping_list_item')
    op.drop_table('shopping_list_item')
    op.drop_index(op.f('ix_inventory_item_status'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_receipt_id'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_product_master_id'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_id'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_expiry_date'), table_name='inventory_item')
    op.drop_table('inventory_item')
    op.drop_index(op.f('ix_product_master_off_product_id'), table_name='product_master')
    op.drop_index(op.f('ix_product_master_id'), table_name='product_master')
    op.drop_index(op.f('ix_product_master_category'), table_name='product_master')
    op.drop_index(op.f('ix_product_master_canonical_name'), table_name='product_master')
    op.drop_table('product_master')
    op.drop_index(op.f('ix_receipt_store_chain'), table_name='receipt')
    op.drop_index(op.f('ix_receipt_processing_status'), table_name='receipt')
    op.drop_index(op.f('ix_receipt_id'), table_name='receipt')
    op.drop_index(op.f('ix_receipt_batch_id'), table_name='receipt')
    op.drop_table('receipt')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
