/**
 * How Kyokki presents itself outside the app (MVP-P2): the Home Screen icon, the browser tab
 * and the web app manifest. Kept in one plain module so `app/manifest.ts` and `app/layout.tsx`
 * cannot drift apart from the files on disk.
 *
 * Colours are the Tailwind palette in `tailwind.config.ts`; change them together.
 * The icons themselves are generated by `frontend/scripts/make_icons.py` - regenerate rather
 * than editing the PNGs by hand.
 */

export const BRAND_NAME = 'Kyokki'

/** primary.600 - the app's accent, and the icon's ground. */
export const BRAND_COLOR = '#228be6'
/** ui.bg */
export const THEME_COLOR_LIGHT = '#ffffff'
/** ui-dark.bg */
export const THEME_COLOR_DARK = '#1a1b1e'
/** The splash colour behind the app while it launches. */
export const BACKGROUND_COLOR = THEME_COLOR_LIGHT

/** Manifest icon sizes. 192 and 512 are what installable-app checks look for. */
export const ICON_SIZES = [192, 512] as const

/** iOS reads apple-touch-icon for the Home Screen and ignores the manifest icons. */
export const APPLE_ICON_SIZE = 180

export function iconPath(size: number): string {
  return `/icons/icon-${size}.png`
}

export const APPLE_ICON_PATH = `/icons/apple-icon-${APPLE_ICON_SIZE}.png`
